export{default as Dashboard}from './dashboard'
export{default as Userpage}from './Userlistpage'
export{default as Listedpage}from './Listedpropertypage'
export{default as Unlistedpage}from './Unlistedpropertypage'
export{default as Detailpage}from './Propertydetailpage'
export{default as Detaillistpage}from './listedpropertydetailspage'