export{default as Homepage}from './Homepage'
export{default as Listpage}from "./Listingpage"
export{default as MYlistpage}from "./Mylistpage"
export{default as Profilepage}from "./Profilepage"
export{default as Savepage}from "./Savedpage"
export{default as Detailpage}from "./Detaildatapage"
export{default as Emailpage}from "./Emailcontactpage"
export{default as Formpage}from "./Addyourhomepage"
export{default as Privacy}from "./Privacy"